# Generated by Django 5.1.1 on 2024-09-18 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtd',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 1, 13, 5, 448475)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 1, 13, 5, 448475)),
        ),
    ]
