# Generated by Django 5.1.1 on 2024-09-21 19:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0003_alter_vtd_updated_at_alter_vtdlog_timestamp_claims'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 4, 8, 50, 334559)),
        ),
        migrations.AlterField(
            model_name='vtd',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 4, 8, 50, 334559)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 4, 8, 50, 334559)),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('readed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 9, 22, 4, 8, 50, 335559))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
