# Generated by Django 5.1.1 on 2024-09-21 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0005_alter_claims_created_at_alter_messages_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtdlog',
            name='from_value',
            field=models.IntegerField(default=0, verbose_name='from_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vtdlog',
            name='to_value',
            field=models.IntegerField(default=0, verbose_name='to_value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 26, 16, 267720)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 26, 16, 267720)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 26, 16, 267720)),
        ),
    ]
