# Generated by Django 5.1.1 on 2024-09-21 20:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0006_vtdlog_from_value_vtdlog_to_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtdlog',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='vtdlog',
            name='to_value',
        ),
        migrations.RemoveField(
            model_name='vtdlog',
            name='vtd_from',
        ),
        migrations.RemoveField(
            model_name='vtdlog',
            name='vtd_to',
        ),
        migrations.AddField(
            model_name='vtdlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 29, 12, 312705)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 29, 12, 312705)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 29, 12, 311704)),
        ),
    ]
