# Generated by Django 5.1.1 on 2024-09-21 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0007_remove_vtdlog_from_value_remove_vtdlog_to_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtdlog',
            name='trade_id',
            field=models.UUIDField(editable=False, null=True, unique=True, verbose_name='trade_id'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 33, 25, 485572)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 33, 25, 485572)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 33, 25, 484571)),
        ),
    ]
