# Generated by Django 5.1.1 on 2024-09-21 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0009_alter_claims_created_at_alter_messages_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 47, 58, 960731)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 47, 58, 961730)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 47, 58, 961730)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 47, 58, 960731)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='trade_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='trade_id'),
        ),
    ]
