# Generated by Django 5.1.1 on 2024-09-21 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0011_alter_claims_created_at_alter_messages_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 58, 3, 197230)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 58, 3, 198230)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 58, 3, 198230)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 5, 58, 3, 197230)),
        ),
    ]
