# Generated by Django 5.1.1 on 2024-09-26 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0014_vtdlog_description_alter_appclaims_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appclaims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 20, 20, 39, 149838)),
        ),
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 20, 20, 39, 149838)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 20, 20, 39, 150838)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 20, 20, 39, 150838)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 20, 20, 39, 148837)),
        ),
    ]
