# Generated by Django 5.1.1 on 2024-09-26 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTDbank', '0015_alter_appclaims_created_at_alter_claims_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtd',
            name='pay_auto',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appclaims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 57, 38, 370158)),
        ),
        migrations.AlterField(
            model_name='claims',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 57, 38, 370158)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 57, 38, 370158)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 57, 38, 371158)),
        ),
        migrations.AlterField(
            model_name='vtdlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 21, 57, 38, 369159)),
        ),
    ]
