# Generated by Django 5.1.2 on 2024-11-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
