# Generated by Django 5.1.3 on 2024-11-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
            ],
        ),
    ]
