# Generated by Django 5.1.2 on 2024-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pageview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
